/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  async redirects() {
    return [
      { source: '/resume-builder', destination: '/en/resume-builder', permanent: true },
      { source: '/cv-builder', destination: '/en/cv-builder', permanent: true },
      { source: '/free-resume-builder', destination: '/en/free-resume-builder', permanent: true },
      { source: '/online-resume-builder', destination: '/en/online-resume-builder', permanent: true },
      { source: '/ats-resume-builder', destination: '/en/ats-resume-builder', permanent: true },
      { source: '/ats-friendly-resume', destination: '/en/ats-resume-builder', permanent: true },
      { source: '/ai-resume-builder', destination: '/en/ai-resume-builder', permanent: true },
      { source: '/ai-cv-builder', destination: '/en/ai-resume-builder', permanent: true },
      { source: '/resume-maker', destination: '/en/resume-maker', permanent: true },
      { source: '/resume-template', destination: '/en/resume-templates', permanent: true },
      { source: '/resume-templates', destination: '/en/resume-templates', permanent: true },
      { source: '/resume-examples', destination: '/en/resume-examples', permanent: true },
      { source: '/cover-letter-generator', destination: '/en/cover-letter-generator', permanent: true },
      { source: '/how-to-write-a-cover-letter', destination: '/en/cover-letter-writing-guide', permanent: true },
      { source: '/cover-letter-writing', destination: '/en/cover-letter-writing-guide', permanent: true },
      { source: '/cover-letter-examples', destination: '/en/cover-letter-generator', permanent: true },
      { source: '/cv-olustur', destination: '/tr/cv-olustur', permanent: true },
      { source: '/cv-olusturucu', destination: '/tr/cv-olusturucu', permanent: true },
      { source: '/ucretsiz-cv-olustur', destination: '/tr/ucretsiz-cv-olustur', permanent: true },
      { source: '/online-cv-olustur', destination: '/tr/online-cv-olustur', permanent: true },
      { source: '/cv-hazirlama', destination: '/tr/cv-hazirlama', permanent: true },
      { source: '/cv-hazirlama-sitesi', destination: '/tr/cv-hazirlama', permanent: true },
      { source: '/ats-uyumlu-cv', destination: '/tr/ats-cv-olusturucu', permanent: true },
      { source: '/ats-cv-olusturucu', destination: '/tr/ats-cv-olusturucu', permanent: true },
      { source: '/ai-cv-olusturucu', destination: '/tr/ai-cv-olusturucu', permanent: true },
      { source: '/yapay-zeka-cv-olusturucu', destination: '/tr/ai-cv-olusturucu', permanent: true },
      { source: '/cv-sablonlari', destination: '/tr/cv-sablonlari', permanent: true },
      { source: '/cv-ornekleri', destination: '/tr/cv-ornekleri', permanent: true },
      { source: '/on-yazi-olusturucu', destination: '/tr/on-yazi-olusturucu', permanent: true },
      { source: '/on-yazi-nasil-yazilir', destination: '/tr/on-yazi-nasil-yazilir', permanent: true },
      { source: '/cover-letter-yazmak', destination: '/tr/on-yazi-nasil-yazilir', permanent: true },
      { source: '/resume-format', destination: '/blog/best-resume-format-for-job-seekers', permanent: true },
      { source: '/how-to-write-a-resume', destination: '/blog/how-to-write-a-resume-in-2026', permanent: true },
      { source: '/entry-level-resume-example', destination: '/en/resume-examples', permanent: true },
      { source: '/internship-resume-example', destination: '/en/resume-examples', permanent: true },
      { source: '/student-resume-example', destination: '/en/resume-examples', permanent: true },
      { source: '/software-engineer-resume-example', destination: '/en/resume-examples/software-engineer', permanent: true },
      { source: '/resume-objective-examples', destination: '/blog/resume-objective-examples-for-beginners', permanent: true },
      { source: '/resume-summary-examples', destination: '/blog/resume-summary-examples-by-industry', permanent: true },
      { source: '/resume-skills-examples', destination: '/blog/resume-skills-examples-employers-want', permanent: true },
    ];
  },
};

export default nextConfig;
